services:
  portfolio:
    build: ./
    image: missael-dev-portfolio
    labels:
      - traefik.backend=portfolio
      - traefik.frontend.rule=Host:missael.dev
      - traefik.port=8181
      - traefik.docker.network=web
      